export const REQUEST_BEFORE = 'REQUEST_BEFORE';
export const REQUEST_AFTER = 'REQUEST_AFTER';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const POST_REGISTER_SUCCESS = 'POST_REGISTER_SUCCESS';
export const CLOSE_CUSTOM_ALERT = 'CLOSE_CUSTOM_ALERT';
export const SET_DEVICE_ID = 'SET_DEVICE_ID';
export const SET_GEO_LOCATION = 'SET_GEO_LOCATION';